// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkndnrsoiuaiqmidtqqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrbmRucnNvaXVhaXFtaWR0cXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDMwODAsImV4cCI6MjA3MjE3OTA4MH0.aBeZ2upyRytZ0XyRLFB2z9B4dDoh54ICo9TWzVkQQa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});